### ISSUE TITLE
Few cdn issues

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#173]
I noticed when you enable cdn some strange things happens with normal links for example:
```css
application\css\default.css
.socket-blue {
    padding-left: 26px;
    background: url(../images/misc/socket_blue.gif) no-repeat left center
}
```
they become 
```css
background: url(https://cdn.fusiongen.net/application/images/misc/socket_blue.gif)
```
resulting in a 404 not found and socket not being displayed at all

![gems](https://user-images.githubusercontent.com/24683355/216961925-11ba4959-79de-4f2c-b892-d5cbaf52908e.png)

also those socket css are loaded twice in both themes and there's no need:

![sqsqsq](https://user-images.githubusercontent.com/24683355/216961644-a21d7173-23b4-4900-8a29-fe727bbbeb39.PNG)
